language: node_js
node_js: node
script: yarn listdiff && yarn lint && yarn build

deploy:
    - provider: npm
      skip-cleanup: true
      email: $NPM_EMAIL
      api_key: $NPM_AUTH_TOKEN
      on:
          repo: magic-akari/seamless-scroll-polyfill
          branch: master
          tags: true
